config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search', to: 'searchs#search'
  get '/prefectures/new', to: 'prefectures#new'
  get '/prefectures', to: 'prefectures#index'
  post '/prefectures', to: 'prefectures#create'

  resources :users, only: %i[show index edit update]

  resources :shops do
    resource :favorites, only: %i[create destroy]
    resources :shop_comments, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
class Shop < ApplicationRecord

  belongs_to :user
  # has_one :prefecture, dependent: :destroy
  # has_one :genre, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # FIXME: After Check Controller
  # accepts_nested_attributes_for :prefecture, :genre

  enum prefecture: {
    "---": 0,
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
    沖縄県: 47
  }

  enum genre: { ドリップ: 1, エスプレッソ: 2 }

  attachment :image, destroy: false

  validates :name, presence: true
  validates :overview, presence: true
  validates :genre, presence: true
  validates :prefecture, presence: true
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(model, content)
    if model == 'prefecture'
      prefecture_id = prefectures.select { |k, _| k.match(/#{content}/) }
      where(prefecture: prefecture_id.values)
    elsif model == 'genre'
      genre_id = genres.select { |k, _| k.match(/#{content}/) }
      where(genre: genre_id.values)
    else
      where('name LIKE ?', "%#{content}%")
    end
  end

  def self.most_favorite(n = 3)
    where(id:
      Favorite.group(:shop_id).order('count(shop_id) desc').limit(n).pluck(:shop_id)
    )
  end

end

app/models/shop_comment.rb
class ShopComment < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :profile_image, destroy: false

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @shop = Shop.find(params[:shop_id])
    favorite = current_user.favorites.new(shop_id: @shop.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    favorite = current_user.favorites.find_by(shop_id: @shop.id)
    favorite.destroy
    # redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    # @shop_rank = Shop.find(Favorite.group(:shop_id).order('count(shop_id) desc').limit(3).pluck(:shop_id))
    @shop_rank = Shop.most_favorite
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def new
    @prefecture = Prefecture.new
  end

  def create
    @prefecture = Prefecture.new(prefecture_params)
    @prefecture.save
    redirect_to prefectures_path
  end

  def index
    @prefectures = Prefecture.all
  end

  private

  def prefecture_params
    params.require(:prefecture).permit(:name)
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController


  def search
    @model = params['model']
    @content = params['content']
    @method = params['method']
    @records = search_for(@model, @content, @method)
  end

  private

  def search_for(model, content, method)
    if model == 'user'
      User.where('name LIKE ?', "%#{content}%")
    else
      Shop.search(model, content)
    end
  end


end

app/controllers/shop_comments_controller.rb
class ShopCommentsController < ApplicationController
  def create
    @shop = Shop.find(params[:shop_id])
    @comment = current_user.shop_comments.new(shop_comment_params)
    @comment.shop_id = @shop.id
    @comment.save
    # redirect_to request.referer
    render :shop_comments
  end

  def destroy
    ShopComment.find_by(id: params[:id]).destroy
    @shop = Shop.find(params[:shop_id])
    render :shop_comments
    # redirect_to request.referer
  end

  private

  def shop_comment_params
    params.require(:shop_comment).permit(:comment)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!

  def new
    @shop_new = Shop.new
    @user = current_user
  end

  def index
    @shops = Shop.all.page(params[:page]).per(3)
    @shop_new = Shop.new
    @user = current_user
  end

  def show
    @shop_new = Shop.new
    @shop = Shop.find(params[:id])
    @user = @shop.user
    @shop_comment = ShopComment.new
  end

  def create
    @shop_new = Shop.new(shop_params)
    @shop_new.user = current_user
    if @shop_new.save!
      redirect_to shop_path(@shop_new), notice: 'You have created shop successfully.'
    else
      @shops = Shop.all.page(params[:page]).per(3)
      @user = current_user
      render 'index'
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    redirect_to shops_path if @shop.user != current_user
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)

      redirect_to shop_path(@shop), notice: 'You have updated shop successfully.'
    else
      render 'edit'
    end
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :image, :overview, :rate, :genre, :prefecture) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @shops = @user.shops.page(params[:page]).per(3)
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      @user = User.find(params[:id])
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shop_comments_helper.rb
module ShopCommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorites.html.erb
<% if shop.favorited_by?(current_user) %>
  <p>
    <%= link_to shop_favorites_path(shop),method: :delete, remote: true do %>
      ♥<%=shop.favorites.count %>
    <%end%>
  </p>
  <%else%>
  <p>
    <%= link_to shop_favorites_path(shop),method: :post, remote: true do %>
      ♡<%= shop.favorites.count %>
    <%end%>
  </p>
<%end%>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @shop.id %>').html("<%= j(render "favorites/favorites", shop: @shop) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @shop.id %>').html("<%= j(render "favorites/favorites", shop: @shop) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-mug-hot"></i><strong>Beans</strong>!</h1>
  </div>
  <div class="row">
    <h5 class="px-3 mx-auto">
      このサイトはおいしいコーヒーショップを共有するためのサイトです<br/>
      見つけたコーヒーショップを見つけたらこのサイトにアップして、他の人にも飲んでもらおう！
    </h5>
  </div>

</div>

app/views/homes/top.html.erb
<div class= "container">
  <div class="row justify-content-md-center">
    <div class="col">
      <h2>Beansにようこそ!</h2>
      <h2>おいしいコーヒーショップを見つけてシェアしよう！</h2>
    </div>
  </div>
</div>


<div class = "container">
  <div class="row">
    <div class="col-md-12 col-md-offset-1">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <!--<#% unless @shop_rank.first.blank? && @shop_rank.second.blank? && @shop_rank.third.blank? %>-->
        <% if @shop_rank.size > = 3 %>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <%= attachment_image_tag @shop_rank.first, :image, :fill, 500, 600, fallback: "no-image-icon.jpg" , class: "d-block top_image mx-auto" %>
              <div class="carousel-caption">
                <h2 class="text-warning bg-white">ランキング1位</h2>
                <h3 class="text-dark bg-white">ShopName</h3>
                <h3 class="bg-white"><%= link_to @shop_rank.first.name, shop_path(@shop_rank.first) %></h3>
              </div>
            </div>
            <div class="carousel-item">
              <% if  @shop_rank.second.present? %>
              <%= attachment_image_tag @shop_rank.second, :image, :fill, 500, 600, fallback: "no-image-icon.jpg" , class: "d-block top_image mx-auto" %>
                <div class="carousel-caption">
                  <h2 class="text-warning bg-white">ランキング2位</h2>
                  <h3 class="text-dark bg-white">ShopName</h3>
  
                  <h3 class="bg-white"><%= link_to @shop_rank.second.name, shop_path(@shop_rank.second) %></3>
                </div>
              <% end %>
            </div>
            <div class="carousel-item">
              <%if  @shop_rank.third.present? %>
                <%= attachment_image_tag @shop_rank.third, :image, :fill, 500, 600, fallback: "no-image-icon.jpg" , class: "d-block top_image mx-auto" %>
                <div class="carousel-caption">
                  <h2 class="text-warning bg-white">>ランキング3位</h2>
                  <h3 class="text-dark bg-white">ShopName</3>
                  <if >
                  <h3 class="bg-white"><%= link_to @shop_rank.third.name, shop_path(@shop_rank.third) %></3>
                </div>
              <% end %>
            </div>
          </div>

        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        <% else %>
         <%= image_tag "top_image.jpg" ,class:"top_image" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/searchs/_form.html.erb
<div class ="text-center">
  <% if user_signed_in? %>
      <%= form_tag(search_path, method: :get) do %>
        <%= text_field_tag 'content' %>
        <%= select_tag 'model', options_for_select({ "User" => "user", "Shop" => "shop" }) %>
        <%= select_tag 'method', options_for_select({ "完全一致" => "perfect",  "前方一致" => "forward_match" ,"後方一致" => "backward_match", "部分一致" => "partial" }) %>
        <%= submit_tag '検索' %>
      <% end %>
  <% end %>
</div>

app/views/searchs/search.html.erb
<div class="container mx-auto">
  <% if @model == 'user' %>
    <h3>【Usersモデルの検索結果】検索ワード：<%= @content %></h3>
    <%= render 'users/index', users: @records %>
  <% else %>
    <h3>【Shopsモデルの検索結果】検索ワード：<%= @content %></h3>
    <%= render 'shops/search_shop', shops: @records %>
  <% end %>
</div>

app/views/shop_comments/_form.html.erb
<%= form_with(model:[shop, shop_comment]) do |f| %>
  <%= f.text_area :comment, size:"60×5",placeholder: "コメント" %>
  <%= f.submit "送信" %>
<%end%>

app/views/shop_comments/_shop_comment.html.erb
<% shop.shop_comments.each do |shop_comment|%>
  <tr>
    <td>
      <p>
        <%= attachment_image_tag(shop.user, :profile_image, :fill, 60, 60, fallback: "no-image-icon.jpg") %>
      </p>
      <%= shop_comment.user.name %>
    </td>
    <td><%= shop_comment.comment %></td>
    <% if shop_comment.user == current_user %>
    <td>
      <%= link_to "Delete",shop_shop_comment_path(shop_comment.shop,shop_comment),method: :delete,remote: true %>
    </td>
    <%end%>
  </tr>
<%end%>

app/views/shop_comments/shop_comments.js.erb
$('#comments_area').html("<%= j(render "shop_comments/shop_comment", shop: @shop,comment: @comment) %>");

$("textarea").val('');

app/views/shops/_edit_form.html.erb
<%= form_with model:shop,local:true do |f| %>
  <div class="form-group">
    <%= f.label :"ショップ" %>
    <%= f.text_field :name, class: 'form-control shop_name' %>
  </div>
  <div class="form-group">
    <%= f.label :"概要" %>
    <%= f.text_area :overview, class: 'form-control shop_overview' %>
  </div>
  <div class="form-group">
    <%= f.label :image%>
    <%= f.attachment_field :image ,class: "form-control-file shop_image" %>
  </div>
  <div class="form-group" >
      <%= f.label :ジャンル選択 %><br>
      <%= f.select :genre, Shop.genres.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="form-group" >
      <%= f.label :地域選択 %><br>
      <%= f.select :prefecture, Shop.prefectures.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div id="rating-form">
    <label>評価：</label>
    <%= f.hidden_field :rate, :value => 'score' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  $('#rating-form').raty({
    size  : 36,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    score: <%= @shop.rate %>,
    scoreName: 'shop[rate]',
  });
</script>

app/views/shops/_form.html.erb
<%= form_with model:shop,local:true do |f| %>
  <div class="form-group">
    <%= f.label :"ショップ" %>
    <%= f.text_field :name, class: 'form-control shop_name' %>
  </div>
  <div class="form-group">
    <%= f.label :"概要" %>
    <%= f.text_area :overview, class: 'form-control shop_overview' %>
  </div>
  <div class="form-group">
    <%= f.label :image%>
    <%= f.attachment_field :image ,class: "form-control-file shop_image" %>
  </div>
  <div class="form-group" >
      <%= f.label :ジャンル選択 %><br>
      <%= f.select :genre, Shop.genres.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div class="form-group" >
      <%= f.label :地域選択 %><br>
      <%= f.select :prefecture, Shop.prefectures.keys, {prompt: '選択してください'}, class: 'form-control btn btn-info' %>
  </div>
  <div id="rating-form">
    <label>評価：</label>
    <%= f.hidden_field :rate, :value => 'score' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

<script>
  $('#rating-form').raty({
    size  : 36,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'shop[rate]',
    half: true,
  });
</script>

app/views/shops/_index.html.erb
<div class = "texts-wrapper">
  <div class="card-deck">
    <% shops.each do |shop| %>
    <div class="col-md-4">
        <div class="card content-card border-dark" style="width: 18rem;">
            <%= link_to user_path(shop.user) do %>
             <%= attachment_image_tag(shop.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" ,class:"card-img-top" )  %>
            <%end%>
            <div class="card-body">
              <h5 class="card-title">ShopName:<br/><%= link_to shop.name, shop_path(shop), class: "shop_#{shop.id}" %></h5>
              <p class="card-text">
                overview:<br/><%= shop.overview %>
              </p>
              <p class="card-text">
                  genre:<br/><%= shop.genre %>
              </p>
              <p class="card-text">
                  prefecture:<br/><%= shop.prefecture %>
              </p>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<div class="mx-aoto">
 <%= paginate @shops %>
</div>

app/views/shops/_search_shop.html.erb
<div class = "texts-wrapper">
    <div class="card-deck">
      <% shops.each do |shop| %>
      <div class="col-md-4">
          <div class="card content-card border-dark" style="width: 18rem;">
              <%= link_to user_path(shop.user) do %>
               <%= attachment_image_tag(shop.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" ,class:"card-img-top" )  %>
              <%end%>
              <div class="card-body">
                <h5 class="card-title">ShopName:<br/><%= link_to shop.name, shop_path(shop), class: "shop_#{shop.id}" %></h5>
                <p class="card-text">
                  overview:<br/><%= shop.overview %>
                </p>
                <p class="card-text">
                    genre:<br/><%= shop.genre %>
                </p>
                <p class="card-text">
                    prefecture:<br/><%= shop.prefecture %>
                </p>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>

app/views/shops/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing shop</h1>
  		<%= render 'edit_form', shop: @shop %>
  		<%= link_to 'Show', shop_path(@shop), class: "shop_#{@shop.id}" %> |
  		<%= link_to 'Back', shop_path, class: "back" %>
  </div>
</div>

app/views/shops/index.html.erb
<div class='container px-4 px-sm-0'>
    <div class='row justify-content-center'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'users/info', user: @user %>

      </div>

        <div class='col offset-md-1'>
          <%= form_with model:@shop_new, local:true do |f|%>
            <%= render 'layouts/error', model: f.object %>
          <% end %>
          <h2>Shops</h2>
          <%= render 'index', shops: @shops %>
        </div>
      </div>


  </div>

app/views/shops/new.html.erb
<div class='container px-4 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'users/info', user: @user %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2 class="mt-3">New shop</h2>
        <%= render 'form', shop: @shop_new %>
      </div>
    </div>
</div>

app/views/shops/show.html.erb
<div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'users/info', user: @user %>
      </div>
      <div class='col-md-6 offset-md-1 '>
    		<h2>shop detail</h2>
    		<div class='d-flex justify-content-center card border-dark'>
              <%= attachment_image_tag @shop, :image, :fill, 60, 60, fallback: "no-image-icon.jpg",class:"card-img-top" %>
          <div class="card-body">
            <div class="card-title">
              User:
              <%= link_to @user.name, user_path(@user) %><br/>
              shop_name:
              <%= link_to @shop.name, shop_path(@shop) %>
            </div>
            <div class="card-text">
                <div>opnion:<%= @shop.overview %></div>
                <div>
                genre:
                  <%= @shop.genre %>
              </div>
              <div>
                prefecture:
                  <%= @shop.prefecture %>
              </div>
              <div id="favorite_buttons_<%= @shop.id%>">
                <%= render "favorites/favorites", shop: @shop %>
              </div>
              <div>コメント数:<%= @shop.shop_comments.count %></div>
              <div>
                <div class="star-group">
                  <div class="detail-review">評価</div>
                  <div class="detail-value", id="star-comf-<%= @shop.id %>"></div> <%# id要素の書き方がポイント %>
                  <div class="eval-star"><%= @shop.rate %>/5点</div> <%# @モデル.カラムで保存された数値を表示 %>
                </div>
              </div>
                <% if @user == current_user  %>
                  <div><%= link_to 'Edit', edit_shop_path(@shop), class: "btn btn-sm btn-success edit_book_#{@shop.id}" %></div>
                  <div><%= link_to 'Destroy', shop_path(@shop), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@shop.id}"%></div>
                <%end%>
            </div>

            </div>
          </div>
        </div>
    </div>
    <div class = "row mt-3">
      <div class = "col-md-3 "></div>
      <div class="col-md-6 offset-md-1">
        <div id = "comments_area">
          <%= render "shop_comments/shop_comment",shop: @shop %>
        </div>
        <div class="new-comment">
          <%= render "shop_comments/form" ,shop: @shop, shop_comment: @shop_comment %>
        </div>
      </div>
    </div>
    <script>
      $('#star-comf-<%= @shop.id %>').raty({      //.idでどの評価であるかを取得
        size: 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        half: true,
        readOnly: true,                             //readOnlyオプションで読み込み専用とする。編集できない。
        score: <%= @shop.rate %>,              //scoreオプションで評価内容を取得
      });
    </script>
</div>

app/views/users/_index.html.erb
<div class="container-user">
  <% users.each do |user| %>
    <div class ="user-item">


        <div><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no-image-user.jpg", size: "100×100", class:"mb-3 rounded-circle image-user" %></div>
        <div><%= user.name %></div>
        <div><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></div>

    </div>
  <% end %>
</div>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" , size:"100×100",class:"mb-3 rounded-circle") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>
<% if user == current_user %>
  <div class='row'>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
    <%= link_to "新規投稿",new_shop_path ,class: "btn btn-outline-secondary btn-block"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :Name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>

    </div>
    <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8 offset-md-2'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class='col-md-10 offset-md-1'>
      <h2>Shops</h2>
      <%= render 'shops/index',shops: @shops %>
    </div>
  </div>
</div>